name: MyAnimeList CI
on:
  workflow_dispatch:
    inputs:
      oauth:
        description: MyAnimeList OAuth Token
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: MyAnimeList CI
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2

      - name: 🔑 Prepare OAuth Token
        run: |
          mkdir -p src/test/java/resources
          echo "${{ github.event.inputs.oauth }}" > src/test/java/resources/oauth.txt

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: ✔ Test with Maven
        run: mvn test